# MCU name
MCU = LPC11U35

BOOTLOADER = kiibohd

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no

CUSTOM_MATRIX = no
# SRC += matrix.c
# SRC += board.c
BOARD = GENERIC_LPC11U35
LAYOUTS = fullsize_ansi
